package banco;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author miriampescadorrojas
 */
public class DetalleCuentaCredito extends javax.swing.JFrame {

    /**
     * Creates new form DetalleCuentaCredito
     */
    public DetalleCuentaCredito() {
        initComponents();
    }
    
    public DetalleCuentaCredito(CuentaCredito c) {
        initComponents();
        mostrarDetalleCredito(c);
    }
    
    public void mostrarDetalleCredito(CuentaCredito c){
       SimpleDateFormat formato = new SimpleDateFormat("dd'/'MM'/'yyyy");
       
       lblNumCuentaC.setText(String.valueOf(c.getNumero())); 
       txtCredito.setText(String.valueOf(c.getSaldoActual()));
       txtInteres.setText(String.valueOf(c.getInteresAnual()));
       txtCorte.setText(c.getfCorte());
       txtPago.setText(c.getfLimite());
       
      
       DefaultTableModel modelo = (new DefaultTableModel(
            null,
            new String [] {
                "Fecha", "Tipo", "Descripcion ", "Saldo Historico"
            }
        ));
        Object o[]=null;
        for (int i = 0; i < c.getMovtos().size() ; i++) {
            modelo.addRow(o);
            Movimiento mvto = c.getMovtos().get(i);
            modelo.setValueAt(formato.format(mvto.getFecha().getTime()), i, 0);
            modelo.setValueAt(mvto.getTipo(), i, 1);
            modelo.setValueAt(mvto.getConcepto(), i, 2);
            modelo.setValueAt(mvto.getSaldoHistorico(), i, 3);
            
        }
       
        TableMvtos.setModel(modelo);
        //jScrollPane2.setViewportView(TableMvtos);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCuenta = new javax.swing.JLabel();
        lblNumCuentaC = new javax.swing.JLabel();
        lblCredito = new javax.swing.JLabel();
        lblInteres = new javax.swing.JLabel();
        lblCorte = new javax.swing.JLabel();
        lblPago = new javax.swing.JLabel();
        txtCredito = new javax.swing.JTextField();
        txtInteres = new javax.swing.JTextField();
        txtCorte = new javax.swing.JTextField();
        txtPago = new javax.swing.JTextField();
        lblMvtos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableMvtos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCuenta.setText("Número de cuenta: ");

        lblNumCuentaC.setText("XXXXXX");

        lblCredito.setText("Credito:");
        lblCredito.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                lblCreditoCaretPositionChanged(evt);
            }
        });

        lblInteres.setText("Interes anual:");

        lblCorte.setText("Fecha corte:");

        lblPago.setText("Fecha pago:");

        txtCredito.setText("jTextField1");
        txtCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditoActionPerformed(evt);
            }
        });

        txtInteres.setText("jTextField2");

        txtCorte.setText("jTextField3");

        txtPago.setText("jTextField4");

        lblMvtos.setText("Movimientos");

        TableMvtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Tipo", "Descripcion ", "Saldo Historico"
            }
        ));
        jScrollPane2.setViewportView(TableMvtos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lblCuenta)
                .addGap(61, 61, 61)
                .addComponent(lblNumCuentaC)
                .addContainerGap(350, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPago)
                        .addGap(18, 18, 18)
                        .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCorte)
                        .addGap(18, 18, 18)
                        .addComponent(txtCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCredito)
                            .addComponent(lblInteres))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMvtos)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuenta)
                    .addComponent(lblNumCuentaC))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMvtos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCredito)
                            .addComponent(txtCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInteres)
                            .addComponent(txtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorte)
                            .addComponent(txtCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPago)
                            .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCreditoCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblCreditoCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCreditoCaretPositionChanged

    private void txtCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreditoActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableMvtos;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCorte;
    private javax.swing.JLabel lblCredito;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblInteres;
    private javax.swing.JLabel lblMvtos;
    private javax.swing.JLabel lblNumCuentaC;
    private javax.swing.JLabel lblPago;
    private javax.swing.JTextField txtCorte;
    private javax.swing.JTextField txtCredito;
    private javax.swing.JTextField txtInteres;
    private javax.swing.JTextField txtPago;
    // End of variables declaration//GEN-END:variables
}
